# environment.yaml

name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - numpy
  - scipy
  - bokeh
  - dask
  - dask-jobqueue
  - dask-labextension
  - distributed
  - cryptography
  - matplotlib
  - pandas
  - pip
  - python-graphviz
  - ipycytoscape
  - pyarrow
  - s3fs
  - zarr
  - pooch
  - xarray
  - mamba
  - asyncssh
  - pip:
    - gdown